// <auto-generated />
using System;
using ChamadosApi.Infrastructure.Persistencia.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChamadosApi.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251015164628_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChamadosApi.Domain.Entities.Chamado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid?>("TecnicoResponsavelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UsuarioAberturaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TecnicoResponsavelId");

                    b.HasIndex("UsuarioAberturaId");

                    b.ToTable("Chamados", (string)null);
                });

            modelBuilder.Entity("ChamadosApi.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("ChamadosApi.Domain.Entities.Chamado", b =>
                {
                    b.HasOne("ChamadosApi.Domain.Entities.Usuario", "TecnicoResponsavel")
                        .WithMany("ChamadosDesignados")
                        .HasForeignKey("TecnicoResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ChamadosApi.Domain.Entities.Usuario", "UsuarioAbertura")
                        .WithMany("ChamadosAbertos")
                        .HasForeignKey("UsuarioAberturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TecnicoResponsavel");

                    b.Navigation("UsuarioAbertura");
                });

            modelBuilder.Entity("ChamadosApi.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("ChamadosAbertos");

                    b.Navigation("ChamadosDesignados");
                });
#pragma warning restore 612, 618
        }
    }
}
